### ISSUE TITLE
Failed to load the linter-jslinter package

### ISSUE THREAD

**Issue by dszmaj** [tensor5/linter-jslinter#1]
[Enter steps to reproduce below:]
1. just load atom

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [linter-jslinter](https://github.com/tensor5/linter-jslinter) package, v0.1.1
### Stack Trace

Failed to load the linter-jslinter package

```
At Unexpected token [

SyntaxError: Unexpected token [
    at Module._compile (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:389:60
    at exit (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\dszma\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -0:22.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".idea"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angular-2-typeScript-snippets, v0.4.6
autocomplete-modules, v1.5.2
file-icons, v1.7.17
linter, v1.11.14
linter-jslinter, v0.1.1
linter-sass-lint, v1.6.1
linter-tidy, v2.1.1
minimap, v4.24.7
minimap-pigments, v0.2.1
pigments, v0.31.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by tensor5** [comment]
Could you open the Developer Tools Ctrl+Shift+I, and try

``` js
require("child_process").execFileSync("npm", ["root", "-g"], {encoding: "utf8"})
```

there?

**Comment by chenasraf** [comment]
@tensor5 Tried that, didn't change anything

**Comment by tensor5** [comment]
@chenasraf did you opt for `Use global JSLinter installation`? If so, I assume you installed JSLinter with `npm install -g jslinter`. Alternatively you can install JSLinter in your home:

```
cd ~/.atom/packages/linter-jslinter
npm install jslinter
```

**Comment by kostadinnm** [comment]
I just like to add these two:
![atom-jslinter-not-working](https://user-images.githubusercontent.com/18436405/35348827-eda2fb10-0141-11e8-9f44-8d4ff71425de.jpg)
![atom-jslinter-working](https://user-images.githubusercontent.com/18436405/35348832-f11e695a-0141-11e8-932b-aaf276c45217.jpg)
In short, I had been trying to add js linting globally, so I tried installing jslinter(npm) globally. As seen from the screenshots, I had to manually set the path to it. Otherwise, local installation works fine :)
Cheers,
Kostadin

**Comment by kostadinnm** [comment]
Addendum: in case anyone's using yarn, here's a hint where to look for:
![2018-02-02 19_11_25-settings c__users_dasbo_projects_es6 atom](https://user-images.githubusercontent.com/18436405/35745738-035d0c0e-084d-11e8-9be3-ad8468ab6ebd.jpg)
